Add extra components for molecule input and viewing
ImperialCollegeLondon/SupraShare pull request #20
Opened 2022-05-05 17:17 UTC by AdrianDAlessandro

This PR creates a few dash components to allow for extra ways to input chemical structures, as well as viewing them. This includes"
 - Uploading a .mol file
 - Viewing a chemical structure image (from uploaded .mol file)
 - Drawing a chemical structure and getting the SMILES string

Currently, they are just added to the bottom of the existing dash app.

2022-05-06 13:24 UTC, AdrianDAlessandro commented
There is a dependancy version issue with the `dash-bio` package required for the Jsme molecular drawer for these models. This will be a problem for any of the other models that are locked in to `scikit-learn<0.20`. We will need to be flexible with this.

2022-05-06 14:12 UTC, cc-a commented
Hmm... this is the sort of thing that makes separation of the front-end (serving the dash app) and the back-end (running the model) compelling.

2022-05-06 15:46 UTC, AdrianDAlessandro commented
That's a good point @cc-a 

Although I don't have any idea how you would make that possible

2022-05-16 15:23 UTC, AdrianDAlessandro commented
> Hmm... this is the sort of thing that makes separation of the front-end (serving the dash app) and the back-end (running the model) compelling.

After some discussion, the decision is to stick with the current approach where front-end and back-end are in the one container. This will be simpler for the researchers to work with.

We will work around this import issue by including the dash-bio objects in a separate module that can be optionally used (i.e. `advanced_widgets`)

2022-05-19 20:40 UTC, AdrianDAlessandro commented
This is ready to be reviewed. It doesn't contain the JSME drawer component, I will have a separate PR for that. The idea is that new apps can be developed by editing these files:
 - `layout.py` - The structure of the html/bootstrap components
 - `callbacks.py` - The interactivity of the components
 - `model.py` - The backend model

There are also some more complicated components in `components.py` that related to uploading a `.mol` file and displaying an image of the molecule. They are not very flexible at the moment, but they're usable and repeatable.

2022-05-23 07:56 UTC, dandavies99 requested changes
This is all looking great - the separation of concerns makes sense and keeps each file a nice length (the bootstrap components can cause them to get a bit unwieldy otherwise.)

I have no suggestions to improve the code itself. I added a placeholder suggestion to the README on the structure of the template - seems like a good place to explain briefly what each file does. Feel free to leave this in as a placeholder for the future or to update it now.

On a similar note, I wonder whether a short, module-level docstring at the top of each file would be useful at this stage.

2022-05-23 07:56 UTC, dandavies99 commented on README.md
```suggestion

## Template structure

The code in this template is separated into several submodules depending on its function. 

TODO: 1 sentence/bullet point per file describing its purpose. 

```mermaid
  graph TD;
      Components-->Layout;
      Model-->Callbacks;
      Callbacks-->App;
      Layout-->App;
```
```

2022-05-23 07:56 UTC, dandavies99 commented on website/layout.py
> +    # Edit this file to edit the text content at the top of the page.
Just to clarify which file file it is that needs editing. 
```suggestion
    # Edit that file to modify the text content at the top of the page.
```

2022-05-23 16:11 UTC, AdrianDAlessandro commented
Works for me!

I also thought a module-level docstring would be helpful. Maybe that and the detail in the README can be tackled at the same time. ie when doing documentation

2022-05-25 07:26 UTC, dandavies99 commented
Yeh good idea, we'll do the docstrings and README details as one.

2022-05-25 07:26 UTC, merged