Ensure consistent Navbar links across apps
ImperialCollegeLondon/SupraShare pull request #24
Opened 2022-05-27 15:43 UTC by AdrianDAlessandro

This PR provides a way to keep the Navbar consistent between all of the apps and link between them. The main detail is that the `app_list.json` file needs to be central too all the containers (I assume this is possible by mounting it as volume to all of them), and also an APP_NAME variable should defined for each container.

This should be merged and then used to make the final cage porosity app before #23 is merged.

2022-05-27 16:03 UTC, AdrianDAlessandro commented
![Screenshot 2022-05-27 at 17 02 02](https://user-images.githubusercontent.com/40875798/170736601-ddb01077-4c00-4f5f-8678-1e8622020045.png)

2022-06-07 09:39 UTC, dandavies99 requested changes
This all looks good to me. I suggest we also add 
```bash
environment:
      - APP_NAME="Is my cage porous?"
```
to `docker-compose.yml` as an example of how the APP_NAME variable would be declared.

2022-06-07 09:39 UTC, dandavies99 commented on website/app.py
> +    with open(filepath, "r") as f:
```suggestion
if (Path(__file__).parent.parent / "app_list.yaml").exists():
    filepath = Path(__file__).parent.parent / "app_list.yaml"
    with open(filepath, "r") as f:
```

2022-06-07 09:39 UTC, dandavies99 commented on website/app.py
> +    with open(filepath, "r") as f:
The walrus operator is ideal here, but not allowed in Python 3.6 😢

2022-06-07 10:40 UTC, merged